import 'package:flutter/material.dart';

const grocery_colorPrimary = Color(0xFF00c97b);
const grocery_colorPrimary_light = Color(0xFFE7FAEE);
const grocery_textColorPrimary = Color(0xFF333333);
const grocery_textGreenColor = Color(0xFF00c97b);
const grocery_textColorSecondary = Color(0xFFAAB3AC);
const grocery_Color_black = Color(0xFF000000);
const grocery_color_white = Color(0xFFFFFFFF);
const grocery_color_red = Color(0xFFC00404);
const grocery_app_background = Color(0xFFE7EFF6);
const grocery_color_yellow = Color(0xFFFFC107);
const grocery_orangeColor = Color(0xFFFE7858);
const grocery_orangeColor_light = Color(0xFFfff0b3);
const grocery_purpleLightColor = Color(0xFF7c5cf4);
const grocery_ShadowColor = Color(0X95E9EBF0);
const grocery_view_color = Color(0xFFB4BBC2);
const grocery_orangeLight_Color = Color(0xFFFAA421);
const grocery_RedLight_Color = Color(0xFFFA4063);
const grocery_Red_Color = Color(0xFFFA244D);
const grocery_icon_color = Color(0xFF747474);
const grocery_light_gray_color = Color(0xFFD0D3D9);
const grocery_DarkBlue_Color = Color(0xFF2233FF);
const grocery_blue_Color = Color(0xFF4A00FF);
const grocery_Pink_Color = Color(0xFFFE2986);

const grocery_blue = Color(0xFF6897BB);
const grocery_darkGrey = Color(0xFF949494);
const grocery_lightGrey = Color(0xFFc9c9c9);
const dating_orange = Color(0xFFFFA500);
