const db_app_name = "Dashboard";
const db1_txt_view_all = "View All";
const db1_lbl_popular = "Popular";
const db1_lbl_filter_your_favourite = "Filter your favourite";
const db1_lbl_recommended_dishes = "Recommended Dishes";
const lbl_breakfast = "Breakfast brot";
const db1_top_picks_for_you = "Top picks for you";
const db1_address = "Mountainview Court \nFresh Meadows, NY 11365";

const db2_lbl_home = "Home";
const db2_lbl_10 = "10";
const db2_lbl_search_here = "Search here";
const db2_lbl_categories = "Categories";
const db2_lbl_view_all = "View all";
const db2_lbl_Featured = "Featured";
const db2_lbl_hot_product = "Hot Products";
const db2_lbl_offers = "Offers";

const db3_lbl_home = "Home";
const db3_lbl_new_arrivals = "New Arrivals";
const db3_lbl_show_all = "Show All";
const db3_lbl_top_trends = "Top Trends";
const db3_lbl_top_sellers = "Top Sellers";

const db4_lbl_listing = " History";
const db4_home = "Home";
const db4_notification = "Notification";
const db4_lbl_profile = "Profile";
const db4_account_number = "Account Number";
const db4_avl_balance = "Available Balance";
const db4_username = "Hi,John";

const db5_hi_juila = "Hi Juila!";
const db5_you_are_in_54_king_ports = "you are in 54 king ports";
const db5_best_destination = "Best Destination";
const db5_see_All = "See all";

const db6_lbl_home = "Home";
const db6_lbl_nearby = "Nearby";
const db6_lbl_booking = "Booking";
const db6_lbl_Offers = "Offers";
const db6_lbl_profile = "Profile";
const db6_username = "Hello,John";
const db6_your_location = "Your Location";
const db6_san_francisco = "San Francisco";
const db6_change = "Change";
const db6_hint_search = "Search Laundry shops by name";
const title_activity_scrolling = "ScrollingActivity";
const action_settings = "Settings";
const db6_lbl_view_all = "View all";
const db6_lbl_view_offers = "View offer";
const db6_lbl_top_services = "Top Services";
const db6_lbl_nearby_laundry = "Popular Laundry Nearby";
const db6_lbl_pkg_offers = "Special package & Offers";

const db7_lbl_my_medical = "My medical";
const db7_lbl_recent_hotspots = "Recent hotspots";
const db7_lbl_today_s_topic = "Today\'s topic";
const db7_lbl_inspection_report = "Inspection Report";
const db7_lbl_lecture = "Lecture";
const db7_lbl_life_medication = "Life Medication";
const db7_lbl_pharmacy = "Pharmacy";
const db7_lbl_inquiry = "Inquiry";
const db7_lbl_multiple_problems = "Multiple Problems";
const db7_lbl_registered = "Registered";
const db7_lbl_just_5_minutes = "Just 5 minutes";

const db8_lbl_rooms = "Rooms";
const db8_lbl_scenes = "Scenes";
const db8_lbl_control_panel = "Control Panel";
const db8_lbl_lightning = "Lightning";
const db8_lbl_19_c = "19.C";
const db8_lbl_temp_outside = "Temp Outside";
const db8_lbl_25_c = "25.C";
const db8_lbl_temp_indoor = "Temp Indoor";
const db8_lbl_29_5_kwh = "29,5 kwH";
const db8_lbl_power_usage_today = "Power usage today";
const db8_lbl_303_kwh = "303 kwH";
const db8_lbl_power_usage_month = "Power usage month";
