import 'package:flutter/material.dart';

const sh_colorPrimary = Color(0xFFf17015);
const sh_colorPrimaryDark = Color(0xFFf17015);
const sh_colorAccent = Color(0xFFf17015);

const sh_textColorPrimary = Color(0xFF212121);
const sh_textColorSecondary = Color(0xFF757575);
const sh_white = Color(0xFFffffff);
const sh_semi_white = Color(0xFFF8F7F7);
const sh_black = Color(0xFF000000);
const sh_view_color = Color(0xFFeaeaea);
const sh_transparent = Color(0xFF00000000);

const sh_background_color = Color(0xFFFCFDFD);
const sh_editText_background = Color(0xFFF1F1F1);
const sh_tomato = Color(0xFFFF6347);
const sh_dots_color = Color(0xFFA5A5A5);
const sh_editText_background_active = Color(0xFFFDE9DA);
const sh_cat_1 = Color(0xFFFA4352);
const sh_cat_2 = Color(0xFF34B5C8);
const sh_cat_3 = Color(0xFFFED76D);
const sh_cat_4 = Color(0xFF0C5A93);
const sh_cat_5 = Color(0xFF3CA69B);
const sh_sidebar_background = Color(0xFFEFEEEF);
const sh_favourite_background = Color(0xFFFFEBEC);
const sh_favourite_unselected_background = Color(0xFFECECEC);
const sh_yellow = Color(0xFFFEBA39);
const sh_light_gray = Color(0xFFECECEC);
const sh_green = Color(0xFF66953A);
const sh_red = Color(0xFFF61929);
const sh_light_green = Color(0xFF81C049);
const sh_more_infoHeading_background = Color(0xFFDDDDDD);
const sh_more_infoValue_background = Color(0xFFF3F3F3);
const sh_item_background = Color(0xFFEFF3F6);
const sh_bg_4star = Color(0xFF78c639);
const sh_light_grey = Color(0xFFFAFAFA);
const sh_checkbox_color = Color(0xFFDFDFDF);
const sh_itemText_background = Color(0xFFF8F8F8);
const sh_track_green = Color(0xFF64B931);
const sh_track_yellow = Color(0xFFECC134);
const sh_track_red = Color(0xFFF61929);
const sh_track_grey = Color(0xFFD3D3D3);
const sh_radiobuttonTint = Color(0xFF4353FA);
const sh_scratch_start_gradient = Color(0xFFe5e5e5);
const sh_scratch_end_gradient = Color(0xFFcccccc);
const sh_shadow_color = Color(0X95E9EBF0);
